const data = {
  products: [
    {
      name: 'Teddy',
      slug: 'teddy',
      category: 'Soft Toys',
      Image: '/image/image-19.png',
      price: 189,
      countInStock: 10,
      brand: 'LM toys',
      rating: 4.5,
      numReviews: 10,
      description: 'skin-friendly soft toys',
    },
    {
      name: 'Whale',
      slug: 'whale',
      category: 'Soft Toys',
      Image: '/image/image-11.png',
      price: 149,
      countInStock: 10,
      brand: 'LM toys',
      rating: 4.5,
      numReviews: 10,
      description: 'skin-friendly soft toys',
    },
    {
      name: 'Dog',
      slug: 'dog',
      category: 'Soft Toys',
      Image: '/image/image-6.png',
      price: 299,
      countInStock: 10,
      brand: 'LM toys',
      rating: 4.5,
      numReviews: 10,
      description: 'skin-friendly soft toys',
    },
    {
      name: 'Reversible Actopus',
      slug: 'reversible actopus',
      category: 'Soft Toys',
      Image: '/image/image-14.png',
      price: 249,
      countInStock: 10,
      brand: 'LM toys',
      rating: 4.5,
      numReviews: 10,
      description: 'skin-friendly soft toys',
    },
  ],
};
export default data;
